In [1]:
# github.com/echtr

In [3]:
import numpy as np

In [7]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [8]:
type(a)

numpy.ndarray

In [11]:
b = np.array([1, 3.14, 2, 4])
b #bütün liste için elemanları tek tipe çevirdi böylelikle kaynaklardan tasarruf ediyor

array([1.  , 3.14, 2.  , 4.  ])

In [12]:
type(b) # tip değişmiyor

numpy.ndarray

In [15]:
# sıfırlardan numpy array oluşturma
np.zeros(10) # 10 tane 0 ekle. - float veritipi
np.zeros(10, dtype = "int") # 10 tane 0 ekle - int veritipi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
# iki boyutlu numpy array oluşturma
np.ones((3,5)) # 1lerden oluşan 3 satır, 5 sütun nparray
# dtype argümanı alabilir

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
# istediğimiz sayı ile 2 boyutlu nparray oluşturma
np.full((3,5), 7) # 3 satır, 5 sütun bir nparray oluştur, her bir hücrede '7' yazsın

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [20]:
# örüntü biçimde nparray oluşturma
np.arange(0, 100, 3) # 0-100 aralığında 3'er artan dizi (0 dahil ama 100 dahil değil)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [21]:
# bir aralığı parçalama
np.linspace(0, 5, 10) # 0 ile 5 aralaığını 10 parçaya böl

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [24]:
# random.normal()
np.random.normal(10, 4, (3, 5))
# ortalaması 10, standart sapması 4 olan 3x5'lik rastgele bir nparray oluştur

array([[ 7.63587258,  5.21330484,  7.42569737,  9.64144914,  7.53905675],
       [ 6.62064365, 13.679259  , 11.37331473,  1.71073506, 10.27233205],
       [ 4.08154326, 14.23512229, 10.07380254, 16.66842429, 12.07542376]])

In [27]:
# random.randint()
np.random.randint(0, 10, (3,3))
# 0 ile 10 arasında değerlerin bulunduğu(0-10 dahil) 3x3'lük nparray oluştur

array([[2, 4, 6],
       [2, 8, 2],
       [0, 3, 5]])