In [1]:
# github.com/echtr

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

In [4]:
np.concatenate([a, b]) # verilen nparray'leri birleştirir

array([1, 2, 3, 4, 5, 6])

In [5]:
np.concatenate([a, b, c])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.concatenate([a, a, b]) # nparray kısıtlaması yok

array([1, 2, 3, 1, 2, 3, 4, 5, 6])

In [11]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])
np.concatenate([a2, a2])
# 2d nparray'leri alt alta olacak şekilde birleştirebilir
# axis, varsayılan olarak 0'dır

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [14]:
np.concatenate([a2, a2], axis = 1) # böylelikle satır bazında birleştirdik
# axis için 0 değeri sütun, 1 değeri ise satırdır

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])