In [1]:
# github.com/echtr

In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3, 99, 99, 4, 5, 6])

In [5]:
np.split(x, [3, 5])
# x adındaki nparray'i [3, 5). index olarak ayır. kalan diğer verileri nparray'e çevir.
# düz bir tahtanın ortasından parça kesince 3 parçaya ayrılır. aynı mantık.

[array([1, 2, 3]), array([99, 99]), array([4, 5, 6])]

In [7]:
a, b, c = np.split(x, [3, 5])
a
# python'da böyle bir değişken atama sistemi mevcut

array([1, 2, 3])

In [16]:
m = np.arange(24).reshape(6, 4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
np.vsplit(m, [2]) # üstten 2. satırın sonundan yatay olarak ayır

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [22]:
np.hsplit(m, [2]) # n-1. sütundan ayır

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]