In [1]:
# github.com/echtr

In [2]:
import numpy as np

In [3]:
v = np.array([3, 4, 6, 1, 1, 2])

In [4]:
np.sort(v)

array([1, 1, 2, 3, 4, 6])

In [5]:
v

array([3, 4, 6, 1, 1, 2])

In [6]:
# np.sort(degisken) methodu, nparray'in yapısını bozmaz

In [7]:
v.sort()

In [8]:
v

array([1, 1, 2, 3, 4, 6])

In [9]:
# degisken.sort() şeklinde kullanımı ise bozar

In [11]:
# iki boyutlu array sıralama
m = np.random.normal(100, 20, (3,3))
m

array([[132.26602214,  67.45639158, 120.62665371],
       [104.17894948,  97.85868379, 105.15826275],
       [ 90.3849523 , 101.66771488,  66.55166883]])

In [12]:
np.sort(m, axis = 0) # sütunları sıralar

array([[ 90.3849523 ,  67.45639158,  66.55166883],
       [104.17894948,  97.85868379, 105.15826275],
       [132.26602214, 101.66771488, 120.62665371]])

In [13]:
np.sort(m, axis = 1) # satırları sıralar

array([[ 67.45639158, 120.62665371, 132.26602214],
       [ 97.85868379, 104.17894948, 105.15826275],
       [ 66.55166883,  90.3849523 , 101.66771488]])