In [1]:
# github.com/echtr

In [2]:
import numpy as np

In [12]:
m = np.random.randint(50, size=10)
m

array([35,  8, 30, 12, 11, 26,  6, 13, 18, 47])

In [13]:
# tek boyutlu dizelerde erişim
m[0]

35

In [14]:
m[0] = 100
m[0]

100

In [15]:
m[-1]

47

In [16]:
# iki boyutlu dizelerde erişim
m = np.random.randint(50, size=(3,5))
m

array([[ 0, 16, 17, 40, 42],
       [15, 39, 37, 15, 22],
       [ 4, 48, 29,  3, 31]])

In [24]:
m[0,0]

0

In [25]:
# m[y, x] => m[satır, sütun]
# her zamanki gibi 0'dan başlar
m[1,0]

15

In [26]:
m[2,2]

29

In [27]:
m[2, 2] = -50
m[2, 2]

-50

In [28]:
# nparray verileri tek tip tuttuğundan dolayı eklenen float bir veri, ondalık kısmı kesilip koyulur
m

array([[  0,  16,  17,  40,  42],
       [ 15,  39,  37,  15,  22],
       [  4,  48, -50,   3,  31]])

In [30]:
m[0, 0] = 1.9
m

array([[  1,  16,  17,  40,  42],
       [ 15,  39,  37,  15,  22],
       [  4,  48, -50,   3,  31]])

In [ ]:
# nparray tipi, oluşturulurken belirlenir. sonradan eklenenler arrayin tipini değiştirmez. 