In [1]:
# github.com/echtr

In [2]:
import numpy as np

In [4]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
a[1::2] # 1. indexten itibaren 2 atlayarak git

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [7]:
# m, matirisin kısaltımı

In [9]:
# iki boyutta slice işlemleri
m = np.random.randint(10, size=(3, 4))
m

array([[6, 6, 0, 1],
       [4, 3, 0, 5],
       [3, 3, 1, 9]])

In [11]:
m[:, 0] # ilk sütuna erişmek

array([6, 4, 3])

In [12]:
m[:, 1] # ikinci sütun

array([6, 3, 3])

In [14]:
m[0,:] # ilk satır

array([6, 6, 0, 1])

In [15]:
m[1,:] # ikinci satır

array([4, 3, 0, 5])

In [17]:
# istediğimiz parçayı seçme
m[0:2, 0:3] # 0. indexten 2. indexe kadar satırları al. / 0. indexten 3. indexe kadar sütunları al

array([[6, 6, 0],
       [4, 3, 0]])

In [20]:
m[::,:2] # tüm satırları al / 2. sütuna kadar al
# m[:, :2]
# m[:, 0:2]

array([[6, 6],
       [4, 3],
       [3, 3]])