In [1]:
# github.com/echtr

In [2]:
import numpy as np

In [8]:
a = np.random.randint(20, size=(6, 6))
a

array([[ 7, 10,  3,  0,  9,  2],
       [ 9,  0,  7, 11,  8, 18],
       [11, 13, 13, 10,  0,  2],
       [ 2,  3, 18,  4, 18, 13],
       [ 3, 15, 12,  1,  4, 10],
       [ 7, 14, 18,  2,  8, 11]])

In [12]:
alt_a = a[0:3, 0:2]
alt_a

array([[ 7, 10],
       [ 9,  0],
       [11, 13]])

In [14]:
alt_a[0, 0] = 100
alt_a

array([[100,  10],
       [  9,   0],
       [ 11,  13]])

In [15]:
a

array([[100,  10,   3,   0,   9,   2],
       [  9,   0,   7,  11,   8,  18],
       [ 11,  13,  13,  10,   0,   2],
       [  2,   3,  18,   4,  18,  13],
       [  3,  15,  12,   1,   4,  10],
       [  7,  14,  18,   2,   8,  11]])

In [17]:
# alt kümede yaptığımız değişiklik, ana kümedede meydana geldi
# bunun seçilen alan ile sınırlı kalması için .copy() metodunu kullanacağız
b = np.random.randint(20, size=(6,6))
b

array([[ 2,  0,  1,  7, 11, 14],
       [10,  7,  4, 13, 18, 13],
       [ 1, 17,  0, 11, 17,  4],
       [10, 10, 17,  4, 18, 18],
       [ 2,  0, 14, 13, 15,  1],
       [ 9, 16, 18, 19,  3, 14]])

In [18]:
alt_b= b[0:3, 0:2].copy()
alt_b

array([[ 2,  0],
       [10,  7],
       [ 1, 17]])

In [20]:
alt_b[0,0] = 100
alt_b

array([[100,   0],
       [ 10,   7],
       [  1,  17]])

In [21]:
b

array([[ 2,  0,  1,  7, 11, 14],
       [10,  7,  4, 13, 18, 13],
       [ 1, 17,  0, 11, 17,  4],
       [10, 10, 17,  4, 18, 18],
       [ 2,  0, 14, 13, 15,  1],
       [ 9, 16, 18, 19,  3, 14]])

In [22]:
# bu şekilde yaptığımız değişiklik ana kümeyi etkilemedi