In [1]:
# github.com/echtr

In [2]:
import numpy as np

In [6]:
a = np.arange(0,30,3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [8]:
a[0], a[3] # böyle birlikte yazdırabiliyormuşuz 

(0, 9)

In [9]:
[a[0], a[3]] # liste halinde

[0, 9]

In [13]:
g = [0, 3]
a[g]
# a'daki 0. ve 3. indexi çağırdık
# buna 'fancy index' deniyor. fancy index adında özel bir işlem yapmadık ama sorunu bu şekilde çözmek fancy index ->
# olarak adlandırılıyor

array([0, 9])

In [14]:
# iki boyutta kullanımı
m = np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
satir = np.array([0, 1])
sutun = np.array([1, 2])
m[satir,sutun]

array([1, 5])

In [16]:
# basit index ile fancy index
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
m[0, [1,  2]] # 0. satır, 1 ve 2. sütun

array([1, 2])

In [26]:
# slice ile fancy index
m[0:, [1, 2]]

array([[1, 2],
       [4, 5],
       [7, 8]])