In [1]:
# github.com/echtr

In [2]:
import numpy as np

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a < 3 # listedeki her eleman için 3'ten küçük olup olmama durumu

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [6]:
a[a < 3] # üstteki ifade için true olan değerleri döndürür

array([0, 1, 2])

In [7]:
a[a > 3]

array([4, 5, 6, 7, 8, 9])

In [8]:
a[a >= 3]

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
a[a == 3] # 3'ler

array([3])

In [11]:
len(a[a > 3]) # 3'ten büyük kaç karakter var?

6

In [12]:
a[a!=3] # 3 olmayan değerler

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [14]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a * 2 # bütün değerleri 2 ile çarp

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
a * a # kare al

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [21]:
a / 5 # listenin tamamı float'a döndü

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [24]:
a **2 # kare al ama neden dtype döndürüyor bilmiyorum

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [25]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])