In [1]:
# github.com/echtr

In [2]:
import numpy as np

In [12]:
# ders 126'da yapılan işlemler fancy index temelliydi. şimdi ise işin arkaplanını inceleyeceğiz.
# ufunc kavramı

In [4]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.subtract(a, 1) # her elemandan 1 çıkar

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [7]:
np.add(a, 1) # her elemana 1 ekle

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.multiply(a, 4) # her elemanı 4 ile çarp

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [11]:
np.divide(a, 4) # her elemanı 4'e böl / yine float tabiiki

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25])

In [16]:
np.power(a, 3) #her elemanın 3. derecesini al
# yine dtype döndürüyor ama bu şuana kadar bir sorun çıkarmadı.

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [17]:
np.mod(a, 2) # her elemanın 2'ye bölümünden kalan

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [18]:
np.absolute([-3, 1, 0, -9]) # mutlak değer alma

array([3, 1, 0, 9])

In [19]:
np.sin(30) # 30 derecenin sinüsü

-0.9880316240928618

In [20]:
np.cos(30) # 30 derecenin kosinüsü

0.15425144988758405

In [28]:
tan = lambda x : np.sin(x)/np.cos(x) 
cot = lambda x : np.cos(x)/np.sin(x)

In [29]:
tan(30)

-6.4053311966462765

In [39]:
np.log(a[1:]) # logaritma al

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [42]:
?np # yapabileceğimiz şeyler
# yorum satırı eklenemiyormuş. aşağıdaki kodu çalıştırınca bilgi kutucuğu gibi bir şey açılıyor

Object `np # yapabileceğimiz şeyler` not found.


In [41]:
?np

In [43]:
# numpy cheat sheet yazarak arşive matematiksel arşive ulaşılabilir
# https://web.itu.edu.tr/iguzel/files/Python_Cheat_Sheets.pdf
# https://s3.amazonaws.com/dq-blog-files/numpy-cheat-sheet.pdf